resources:
- name: repo
  type: git
  source:
    uri: https://gitea.fabiv.pw/fborries/utilities.git

jobs:
- name: generate-pipelines
  plan:
  - get: repo
    trigger: true
  - task: find-pipelines
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: debian
          tag: latest
      outputs: 
      - name: "pipeyaml"
      inputs: 
      - name: "repo"
      run:
        path: sh
        args:
        - "-exc"
        - |
          cd repo
          find . -iwholename ./.concourse.yaml -prune -o -iname .concourse.yaml \
            -printf '- {"name":"%h","value":"%P"}\n' \
          | sed 's/\"\.\//\"/' \
          | awk -F'"' -v OFS='"' '{sub("/", ".", $4)}{ print $0}' \
          > ../pipeyaml/pipelines.yaml
  - load_var: pipelinelist
    file: pipeyaml/pipelines.yaml
  - across:
    - var: pipeline
      values: ((.:pipelinelist))
    set_pipeline: utilities.((.:pipeline.name))
    file: repo/((.:pipeline.value))
